org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.76
neo_version_range=[26.1.2.76,)
loader_version_range=[4,)

## Mod Properties
mod_id=havencreatorcam
mod_name=HavenCreatorCam
mod_license=All Rights Reserved
mod_version=1.0.4
mod_group_id=net.cathienova
mod_authors=CathieNova
mod_description=Adds a Hotkey to view your face.