
modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="havencreatorcam"
version="${file.jarVersion}"
displayName="Haven Creator Cam"
logoFile="examplemod.png"
credits=""
authors="CathieNova"
description='''${mod_description}'''
[[dependencies.havencreatorcam]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.havencreatorcam]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="CLIENT"
