modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
    modId="havencreatorcam"
    version="${mod_version}"
    displayName="${mod_name}"
    logoFile="havencreatorcam_logo.png"
    authors="${mod_authors}"
    description='''${mod_description}'''
[[dependencies.havencreatorcam]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="CLIENT"
[[dependencies.havencreatorcam]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"