
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="havencreatorcam"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"

description='''${mod_description}'''
[[dependencies.havencreatorcam]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="CLIENT"
[[dependencies.havencreatorcam]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"